apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: store-front-ingress
  namespace: test-tls
  annotations:
    kubernetes.azure.com/tls-cert-keyvault-uri: https://kv-bcp-njff4zl3-itn.vault.azure.net/certificates/intE2ECert/48ed435fdfe347479f883975a301617f
spec:
  ingressClassName: nginx-internal
  rules:
  - host: bu0001a0008-00.aks-ingress.contoso.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: store-front
            port:
              number: 80
  - host: public-wai.aks-ingress.contoso.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: public-wai
            port:
              number: 80
  tls:
  - hosts:
    - public-wai.aks-ingress.contoso.com
    - bu0001a0008-00.aks-ingress.contoso.com
    secretName: keyvault-store-front-ingress