# This is a SecretProviderClass example using user-assigned identity to access your key vault
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: keyvault-secret-class
  namespace: wordpress
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"          
    userAssignedIdentityID: "9a9c4a5d-3a74-4833-96d1-3430b2ba3c0f"
    keyvaultName: "kv-test-njff4zl3-itn"     
    cloudName: ""                         
    objects:  |
      array:
        - |
          objectName: mysql-database-user
          objectType: secret
          objectVersion: ""
        - |
          objectName: mysql-database-host
          objectType: secret              
          objectVersion: ""              
        - |
          objectName: mysql-database-password
          objectType: secret
          objectVersion: ""              
        - |
          objectName: mysql-database-name
          objectType: secret              
          objectVersion: ""
        - |
          objectName: letsentest
          objectType: secret
    tenantId: "ea940877-ee38-4d12-9bc2-9d1f97d25dd7" 
  secretObjects:                       
    - secretName: keyvault-secrets
      data:
      - key: mysql-database-user        
        objectName: mysql-database-user  
      - key: mysql-database-host
        objectName: mysql-database-host
      - key: mysql-database-password
        objectName: mysql-database-password
      - key: mysql-database-name
        objectName: mysql-database-name
      type: Opaque                       
    - secretName: ingress-tls-wordpress
      data: 
        - objectName: letsentest
          key: tls.key
        - objectName: letsentest
          key: tls.crt
      type: kubernetes.io/tls